### PR TITLE
Update gdnative interface for beta5 (commit 89a33d28f)

### PR DESCRIPTION
**Pull request by Superbelko**
The rest will come later, it will require some effort to make it work again...

### CODE REVIEW

**Comment by al1-ce** [comment]
How do you even know what to change

**Comment by Superbelko** [comment]
See git log for this file
https://github.com/godotengine/godot/blob/master/core/extension/gdnative_interface.h

Commit version is stated in godot editor console and editor launcher, track it for a that commit and voila.

Of course this probably can be simply replaced with ImportC, however I prefer to have a real D file for better IDE experience.

**Comment by al1-ce** [comment]
Noted

**Comment by Superbelko** [comment]
I updated the generator, now I need to adjust registration code, but I expect to finish it today if everything goes smooth.

**Comment by Superbelko** [comment]
I had to remove most of auto encoding for strings and replaced with simple helper methods generation.

Unfortunately only type registration is working at this moment, methods and other members doesn't registered at all, will look into it today.

**Pull request merged**
