### PR TITLE
simplify PackedArray data access

### LINKED ISSUE #166: PackedByteArray.data corrupts if the PackedByteArray object goes out of scope earlier
**Describe the bug**
accessing data from
```d
auto data = FileAccess.getFileAsBytes(path).data;
writeln(data[0 .. 1000]); // <-- potentially corrupt memory
```
breaks because it accesses corrupt / freed memory, since the PackedByteArray is destructed immediately on this call.

To access it correctly you need to do:
```d
auto bytes = FileAccess.getFileAsBytes(path);
auto data = bytes.data;
writeln(data[0 .. 1000]);
```

the PackedByteArray object returned by `FileAccess.getFileAsBytes(path)` needs to stay alive as long as the `.data` pointer/buffer that you can read off it.

**Expected behavior**
A compiler error should occur when attempting to outlive variables (e.g. using dip1000 / return/scope attributes)

**Plaform (please complete the following information):**
 - OS: ArchLinux
 - Build target: Desktop Linux

### PR DESCRIPTION
**Pull request by WebFreak001**
does not fix #166 on its own yet, since the caller would need to be `@safe` and all the functions in godot-dlang are `@system` so it's not really feasible to work with it with `@safe` code.

The `return` attribute would already fix the issue though, if the caller could be annotated `@safe` for the remaining APIs.

### CODE REVIEW

**Comment by Superbelko** [comment]
I have some fix in packedarray that I haven't pushed yet. Will need to see this PR closely.

**Comment by Superbelko** [comment]
Ok, this is different thing. 
My local fixes related to PackedArray properties which is broken in master.

**Comment by WebFreak001** [comment]
this changes the API to make `data` be `T[]` instead of `T*`, which I think makes more sense in D.

Usually this should be transparent + added bounds checks, unless for overload picking and minor stuff like that.

The ranges work differently now, but I think they are more useful now.

**Comment by Superbelko** [comment]
Ok got it, but just to make sure we don't mess up it even more - this Read and Write structs is just reflects how it is works internally in godot itself and godot-cpp, so basically in C++ it does bounds checks by using another struct that may also have read/write barriers.
So it might currently work just by coincidence, but there is no guarantees that it will stay that way. 
I don't have any objection though.

**Comment by WebFreak001** [comment]
I don't think the C++ Read/Write structs exist anymore

the API how I implemented it now is what I saw on current master

**Comment by WebFreak001** [comment]
see https://github.com/godotengine/godot-cpp/blob/1c19d627aac5410b115bfe80277bc3c916a8420d/src/variant/packed_arrays.cpp#L54

**Comment by Superbelko** [comment]
Ok, got it.

**Pull request merged**
